# Generated by Django 5.1.4 on 2025-01-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='auditlog',
        ),
        migrations.AlterModelTable(
            name='consultationmaterials',
            table='consultation_materials',
        ),
        migrations.AlterModelTable(
            name='consultationresult',
            table='consultation_result',
        ),
        migrations.AlterModelTable(
            name='consultations',
            table='consultaions',
        ),
        migrations.AlterModelTable(
            name='consultationstatus',
            table='consultation_status',
        ),
        migrations.AlterModelTable(
            name='consultationtypes',
            table='consultation_type',
        ),
        migrations.AlterModelTable(
            name='levelupgraderequests',
            table='level_upgrade_requests',
        ),
        migrations.AlterModelTable(
            name='levelupgradestatus',
            table='level_upgrade_status',
        ),
        migrations.AlterModelTable(
            name='loginhistory',
            table='loginhistory',
        ),
        migrations.AlterModelTable(
            name='management',
            table='management',
        ),
        migrations.AlterModelTable(
            name='notificaitons',
            table='notificaitons',
        ),
        migrations.AlterModelTable(
            name='nurse',
            table='nurse',
        ),
        migrations.AlterModelTable(
            name='systemconfiguration',
            table='system_configuration',
        ),
    ]
