# Generated by Django 5.1.4 on 2025-01-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='consultationmaterials',
            old_name='consultation_id',
            new_name='consultation',
        ),
        migrations.RenameField(
            model_name='consultationresult',
            old_name='consultation_id',
            new_name='consultation',
        ),
        migrations.RenameField(
            model_name='consultationresult',
            old_name='nurse_id',
            new_name='nurse',
        ),
        migrations.RenameField(
            model_name='consultations',
            old_name='consultation_type_id',
            new_name='consultation_type',
        ),
        migrations.RenameField(
            model_name='consultations',
            old_name='management_id',
            new_name='management',
        ),
        migrations.RenameField(
            model_name='consultations',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='levelupgraderequests',
            old_name='management_id',
            new_name='management',
        ),
        migrations.RenameField(
            model_name='levelupgraderequests',
            old_name='nurse_id',
            new_name='nurse',
        ),
        migrations.RenameField(
            model_name='levelupgraderequests',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='management',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='materialreadstatus',
            old_name='consultation_materials_id',
            new_name='consultation_materials',
        ),
        migrations.RenameField(
            model_name='materialreadstatus',
            old_name='nurse_id',
            new_name='nurse',
        ),
        migrations.RenameField(
            model_name='notificaitons',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
