# Generated by Django 5.1.4 on 2025-01-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_id_auditlog_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='user_id',
            new_name='user',
        ),
    ]
