# Generated by Django 5.1.4 on 2025-01-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_id_nurse_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultations',
            table='consultations',
        ),
    ]
