# Generated by Django 5.1.4 on 2025-01-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_consultations_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='user_id',
            new_name='user',
        ),
    ]
