# Generated by Django 5.1.4 on 2025-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_id_management_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelreferences',
            name='next_level',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
