# Generated by Django 5.1.4 on 2025-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_levelreferences_next_level'),
    ]

    operations = [
        migrations.RunSQL("""
                        ALTER TABLE level_reference
                        ADD COLUMN temp_level_reference INTEGER;
                        
                        UPDATE level_reference
                        SET temp_level_reference = 12;
                        
                        ALTER TABLE level_reference
                        DROP COLUMN required_time;
                        
                        ALTER TABLE level_reference
                        RENAME COLUMN temp_level_reference TO required_time;
                        """),
        migrations.AlterField(
            model_name='levelreferences',
            name='required_time',
            field=models.IntegerField(),
        ),
    ]
