# Generated by Django 5.1.4 on 2025-01-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_levelreferences_required_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelreferences',
            old_name='required_time',
            new_name='required_time_in_month',
        ),
    ]
