# Generated by Django 5.1.4 on 2025-01-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_required_time_levelreferences_required_time_in_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelReferences',
            new_name='LevelReference',
        ),
    ]
