# Generated by Django 5.1.4 on 2025-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_levelreferences_levelreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelupgraderequests',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
