# Generated by Django 5.1.4 on 2025-01-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_levelupgraderequests_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.CharField(max_length=10)),
                ('to_level', models.CharField(max_length=10)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('years_of_service', models.IntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nurse')),
            ],
        ),
    ]
