# Generated by Django 5.1.4 on 2025-01-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_levelhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelhistory',
            options={'ordering': ['nurse']},
        ),
        migrations.AlterModelTable(
            name='levelhistory',
            table='level_history',
        ),
    ]
