# Generated by Django 5.1.4 on 2025-01-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_levelhistory_created_at_levelhistory_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelhistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.levelupgradestatus'),
        ),
        migrations.AlterField(
            model_name='levelhistory',
            name='from_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_level', to='core.levelreference'),
        ),
        migrations.AlterField(
            model_name='levelhistory',
            name='to_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_level', to='core.levelreference'),
        ),
    ]
