# Generated by Django 5.1.4 on 2025-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_levelhistory_status_alter_levelhistory_from_level_and_more'),
    ]

    operations = [
                migrations.RunSQL("""
                        ALTER TABLE Nurse
                        ADD COLUMN temp_years_of_service INTEGER;
                        
                        UPDATE Nurse
                        SET temp_years_of_service = (now()::date  - hire_date ::date);
                        
                        ALTER TABLE Nurse
                        DROP COLUMN years_of_service;
                        
                        ALTER TABLE Nurse
                        RENAME COLUMN temp_years_of_service TO years_of_service;
                        """),
        migrations.AlterField(
            model_name='nurse',
            name='years_of_service',
            field=models.IntegerField(),
        ),
    ]
