# Generated by Django 5.1.4 on 2025-02-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_nurse_years_of_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='documnets/')),
            ],
        ),
        migrations.RemoveField(
            model_name='consultationmaterials',
            name='file_path',
        ),
        migrations.AddField(
            model_name='consultationmaterials',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materials'),
        ),
    ]
