# Generated by Django 5.1.4 on 2025-02-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_materials_remove_consultationmaterials_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationmaterials',
            name='file',
        ),
        migrations.AddField(
            model_name='consultationmaterials',
            name='file',
            field=models.ManyToManyField(null=True, to='core.materials'),
        ),
    ]
