# Generated by Django 5.1.4 on 2025-02-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_consultationmaterials_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationmaterials',
            name='title',
        ),
        migrations.AlterField(
            model_name='consultationmaterials',
            name='file',
            field=models.ManyToManyField(to='core.materials'),
        ),
    ]
