# Generated by Django 5.1.4 on 2025-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_materials_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='size_readable',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
