# Generated by Django 5.1.4 on 2025-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_materials_size_readable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
