# Generated by Django 5.1.4 on 2025-02-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_materials_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultationmaterials',
            old_name='consultation',
            new_name='counseling',
        ),
        migrations.AlterField(
            model_name='materials',
            name='size_readable',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='consultationmaterials',
            table='counsseling_materials',
        ),
    ]
