# Generated by Django 5.1.4 on 2025-02-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_consultation_consultationmaterials_counseling_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultationmaterials',
            table='counseling_materials',
        ),
    ]
