# Generated by Django 5.1.4 on 2025-02-18 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_consultationmaterials_counselingmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
