# Generated by Django 5.1.4 on 2025-02-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_materials_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materials',
            table='materials',
        ),
    ]
