# Generated by Django 5.1.4 on 2025-02-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_counselingmaterials_file_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counselingtypes',
            table='counseling_type',
        ),
    ]
