# Generated by Django 5.1.4 on 2025-02-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_counselingtypes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'counseling_status',
            },
        ),
        migrations.AlterField(
            model_name='counseling',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.counselingstatus'),
        ),
        migrations.DeleteModel(
            name='ConsultationStatus',
        ),
    ]
