# Generated by Django 5.1.4 on 2025-02-22 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_counselingstatus_alter_counseling_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationResult',
            new_name='CounselingResult',
        ),
        migrations.AlterModelTable(
            name='counselingresult',
            table='counseling_result',
        ),
    ]
