# Generated by Django 5.1.4 on 2025-02-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_consultationresult_counselingresult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='name',
        ),
    ]
