# Generated by Django 5.1.4 on 2025-02-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_department_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='role_name',
            new_name='name',
        ),
    ]
