# Generated by Django 5.1.4 on 2025-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_role_name_roles_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
