# Generated by Django 5.1.4 on 2025-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_nurse_profile_picture_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='level_upgrade_date',
            field=models.DateField(null=True),
        ),
    ]
