# Generated by Django 5.1.4 on 2025-02-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_nurse_level_upgrade_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelUpgradeRequests',
        ),
    ]
