# Generated by Django 5.1.4 on 2025-02-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_delete_levelupgraderequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreadstatus',
            name='consultation_materials',
        ),
        migrations.RemoveField(
            model_name='materialreadstatus',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='notificaitons',
            name='user',
        ),
        migrations.DeleteModel(
            name='CounselingMaterials',
        ),
        migrations.DeleteModel(
            name='MaterialReadStatus',
        ),
        migrations.DeleteModel(
            name='Notificaitons',
        ),
    ]
