# Generated by Django 5.1.4 on 2025-02-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_materialreadstatus_consultation_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='current_level_start_date',
            field=models.DateField(null=True),
        ),
    ]
