# Generated by Django 5.1.4 on 2025-02-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_nurse_current_level_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelhistory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
