# Generated by Django 5.1.4 on 2025-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_levelhistory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='file_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
